# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: publysher/hugo

test:
  script:
  - 'ln -s `pwd` exampleSite/themes/ranger'
  - cd exampleSite
  - hugo
  artifacts:
    paths:
    - exampleSite/public

pages:
  stage: deploy
  script:
  - 'ln -s `pwd` exampleSite/themes/ranger'
  - cd exampleSite
  - hugo
  - mv public ../public
  artifacts:
    paths:
    - public
  only:
  - master