# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ranger"
license = "MIT"
licenselink = "https://gitlab.com/computerfr33k/ranger-hugo-theme/blob/master/LICENSE.md"
description = "Ranger theme ported to Hugo by Eric Pfeiffer"
homepage = "https://gitlab.com/computerfr33k/ranger-hugo-theme"
tags = ["Ranger", "Hugo", "Landing Page"]
features = ["", "", ""]
min_version = 0.17

[author]
  name = "Eric Pfeiffer"
  homepage = "https://www.ericpfeiffer.me"

[original]
  name = "Ranger"
  homepage = "https://freehtml5.co/ranger-free-website-template-using-bootstrap/"
