languageCode = "en-us"
title = "Ranger"
baseURL = "https://computerfr33k.gitlab.io/ranger-hugo-theme"
theme = "ranger"

[params]
  # Meta
  author = "FreeHTML5.co"
  description = ""
  email = ""
  
  [params.social]
    twitter = "https://twitter.com/username"
    facebook = ""
    youtube = ""
    pinterest = ""
    linkedin = ""
    instagram = ""
    dribbble = ""
  
  # Navigation
  [params.navigation]
    brand = "Ranger<span>.</span>"
    home = "Home"
    services = "Services"
    screenshots = "Screenshots"
    tour = "Tour"
    features = "Features"
    testimonials = "Testimonials"
    pricing = "Pricing"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
    
    # Hero section
  [params.hero]
    title = "App for IOS"
    subtitle = '100% Free Fully Responsive HTML5 Bootstrap Template. Crafted with love by the fine folks at <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a>'

    # Services section
  [params.services]
    enable = true
    title = "Our Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  [params.screenshots]
    enable = true
    title = "App Screenshots"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  [params.tour]
    enable = true
    
  [params.features]
    enable = true
    title = "Features"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  [params.pricing]
    enable = true

  [params.cta]
    enable = true

  [params.footer]
    enable = true
    copyright = '&copy; 2015 Free Website Template<a href="index.html">Ranger</a>. All Rights Reserved. <br> Free HTML5 Template by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> | Images by <a href="http://pexels.com/" target="_blank">Pexels</a>'
